### ISSUE TITLE
 Where fzip.swc should be placed exactly ? Or I'm doing something wrong?

### ISSUE THREAD

**Issue by webmatrixxxl** [childoftv/as3-xlsx-reader#5]
Hi man! I'm trying to compile your code and test it. You mentioned that fzip.swc should be placed in ' project library path' but I'm sure what is it.

I downloaded fzip from github and the only way to compile your project is placing fzip-master/src/deng folder into flex_sdk_4.6/projects/as3-xlsx-reader-master/src/

but when I start LoadXLSXExample.swf it is blank..

I get this message when compiling:
https://infinit.io/_/vjfD9Lg

Thank you!

**Comment by webmatrixxxl** [comment]
ok... the problem is not fzip.swc
 I tried ./mxmlc  -library-path+=lib ../projects/as3-xlsx-reader-master/src/LoadXLSXExample.as 
with fzip.swc in it but still blank page..

**Comment by childoftv** [comment]
Hi there!

The only output is given via trace so you should try this: 

http://stackoverflow.com/questions/17629025/running-swf-from-the-command-line-and-getting-trace-output-to-the-console

and you should see: 

"[SWF] LoadXLSXExample.swf - 28,836 bytes after decompression
Attempting to load Example Spreadsheet.xlsx
'Example Spreadsheet.xlsx' unzipped and loaded: 11 files are inside the xlsx
getCell:A3 3 A
Cell A3=Hello Excel
[Unload SWF] LoadXLSXExample.swf
"

Some output in the swf itself would be good so I'll add that shortly along with a few tweaks to bring this project up to 2106

**Comment by childoftv** [comment]
I was able to confirm this but ran into an issue with the security sandbox:

```
(fdb) run /Users/ben/code/scratch/LoadXLSXExample.swf
Attempting to launch and connect to Player using URL
/Users/ben/code/scratch/LoadXLSXExample.swf
Player connected; session starting.
Set breakpoints and then type 'continue' to resume the session.
[SWF] Users:ben:code:scratch:LoadXLSXExample.swf - 28,836 bytes after decompression
(fdb) continue
[trace] Attempting to load Example Spreadsheet.xlsx
[trace] *** Security Sandbox Violation ***
[trace] Connection to file:///Users/ben/code/scratch/Example Spreadsheet.xlsx halted - not permitted from file:///Users/ben/code/scratch/LoadXLSXExample.swf
[Fault] exception, information=SecurityError: Error #2148: SWF file file:///Users/ben/code/scratch/LoadXLSXExample.swf cannot access local resource file:///Users/ben/code/scratch/Example Spreadsheet.xlsx. Only local-with-filesystem and trusted local SWF files may access local resources.
Execution halted in 'LoadXLSXExample.swf' at 0xffffffff (-1)
```
This was fixed by compiling the swf with `-use-network=false` to allow for the local sandbox
```
(fdb) run file:///Users/ben/code/scratch/LoadXLSXExample.swf
Attempting to launch and connect to Player using URL
file:///Users/ben/code/scratch/LoadXLSXExample.swf
Player connected; session starting.
Set breakpoints and then type 'continue' to resume the session.
[SWF] Users:ben:code:scratch:LoadXLSXExample.swf - 28,836 bytes after decompression
(fdb) continue
[trace] Attempting to load Example Spreadsheet.xlsx
[trace] 'Example Spreadsheet.xlsx' unzipped and loaded: 11 files are inside the xlsx
[trace] getCell:A3 3 A
[trace] Cell A3=Hello Excel
```

**Comment by webmatrixxxl** [comment]
Great! Thank you.
