### ISSUE TITLE
Browse for the file

### ISSUE THREAD

**Issue by smithalbs** [childoftv/as3-xlsx-reader#6]
What if I want to browse for the file to be uploaded? How can I get the path of the file?

**Comment by childoftv** [comment]
See the example in https://github.com/childoftv/as3-xlsx-reader/blob/master/projects/as3-xlsx-reader-example/src/LoadXLSXExample.as

particularly: 

```
excel_loader.addEventListener(Event.COMPLETE, loadingComplete);
			
//Load the file
excel_loader.load("Example Spreadsheet.xlsx");
```
If you want to browse for file checkout this:

https://www.kirupa.com/developer/as3/loading_files_disk_pg1.htm 

and pass the filepath to `excel_loader.load()` once you have it

**Comment by smithalbs** [comment]
Hi-Thanks for the response 
My requirement is to browse and upload xls and xlsx file formats. I am unable to retrieve the path when I browse- It works well when I hardcode the path. Please see the code 

                      private function browseForFile():void
			{		
				
				//clear the graphics layer of highlighted factor3/4
				clear();				
				fr = new FileReference();								
				fr.addEventListener(Event.SELECT, frSelect);				
				fr.addEventListener(Event.COMPLETE, frComplete);
				//for xlsx
				excel_loader.addEventListener(Event.COMPLETE, xlsxloadingComplete);				
				var fileFilter:FileFilter = new FileFilter("All Files","*");  
				fr.browse([fileFilter]);
				
			}	 

                      private function frSelect(evt:Event):void{	
				
				try {
					__uploadFile__.text = fr.name;  
					if(evt.currentTarget.type==".xlsx"){  
						//excel_loader.load("C:/temp/new1.xlsx"); //this works - but, how can I get the path of the file browsed?
						 
					}
					else{	 
						fr.load();
					}
											
				}
				catch (e:Error) {
					trace (e.message);					
				}
			}
	
Please help

**Comment by childoftv** [comment]
Ah I see so you're doing this within a browser... 

I think according to this: 
http://stackoverflow.com/questions/1811736/can-flash-action-script-read-and-write-local-file-system

You should be able to first load the file reference with fr.load and then get a file, convert it to a byte array and then use: [loadFromByteArray](https://github.com/childoftv/as3-xlsx-reader/blob/master/src/com/childoftv/xlsxreader/XLSXLoader.as#L124)

**Comment by smithalbs** [comment]
Thanks a lot! It works now :)

**Comment by childoftv** [comment]
Rad :+1:
